### ISSUE TITLE
--volume command doesn't protect against volume > 100

### ISSUE THREAD

**Issue by wootosmash** [zenril/burger-overlay#10]
It's possible to pass a volume larger than 100 via the --volume command

**Comment by zenril** [comment]
The range that the JS Sound API is expecting is 0 - 1.

All volume gets passed through this.
So, in fact, the burger bar can accept volumes between 0-1 and 1.1 - 100.
Then any value goes through `Math.min(v, 1);` so if v is bigger than 1, it won't be after this.
    
    static normalizeVolume(v){
        if(isNaN(v)) return false;
        if(!isNaN(v) && v > 1) v = (v / 100);
        return Math.min(v, 1);
    }

**Comment by wootosmash** [comment]
Heyyy i missed that
We went digging to confirm that it checked 0-100 and couldn't find anything explicit that referred to the 100 ceiling.

**Comment by zenril** [comment]
who is we :D?

**Comment by wootosmash** [comment]
@moobler checked out the code
